### ISSUE TITLE
[server-04] Create Initialization Data.

### ISSUE THREAD

**Issue by synoet** [nysteo/Aero#8]
There are a few things that we will add to our database manually.

For example, Airport models. we will write a script that will push all airports to our db.

Make a JSON file will 25-50 Airports.

Identify other models that we can complete now.

**Comment by hammamiomar** [comment]
[AirportData.txt](https://github.com/nysteo/Aero/files/6290783/AirportData.txt)

For now, there are 50 airports but I have data for 1512 USA airports. Other models that can be completed  are airlines, airplanes, customers, and flights
